site_name: JM Ebia
# site_url: https://jmebia.com  # Optional, for SEO and linking
site_author: JM Ebia
site_description: Developer Portfolio

theme:
  name: material
  logo: /assets/me.png
  palette:
  # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
  font:
    text: Cascadia Mono
    code: Fira Code
  features:
    - navigation.expand
    - navigation.top
    - navigation.tabs
    - toc.integrate
    - blog  # Enables blog layout
    - content.code.annotate

nav:
  - Home: index.md
  - Projects:
      - Overview: projects/index.md
  - CV: cv.md

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - meta
  - tables
  - attr_list

extra_css:
  - assets/stylesheets/custom.css  # Optional custom styling

extra_javascript:
  - assets/scripts/custom.js       # Optional custom JS

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jmebia
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jmebia/
  generator: false
  favicon: assets/me.png